// frontend-react/src/components/ItineraryForm.tsx
import { useState } from 'react';
import type { CreateItineraryDTO, Itinerary } from '../types';
import './ItineraryForm.css';

interface ItineraryFormProps {
  initialData?: Itinerary;
  onSubmit: (data: CreateItineraryDTO) => void | Promise<void>;
  onCancel?: () => void;
}

const ItineraryForm = ({ initialData, onSubmit, onCancel }: ItineraryFormProps) => {
  const [formData, setFormData] = useState<CreateItineraryDTO>({
    title: initialData?.title || '',
    description: initialData?.description || '',
    startDate: initialData?.startDate?.split('T')[0] || '',
    endDate: initialData?.endDate?.split('T')[0] || '',
    destination: initialData?.destination || '',
    status: initialData?.status || 'draft',
    budget: initialData?.budget || undefined,
    currency: initialData?.currency || 'USD',
  });

  const [loading, setLoading] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: name === 'budget' ? (value ? parseFloat(value) : undefined) : value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      await onSubmit(formData);
    } finally {
      setLoading(false);
    }
  };

  return (
    <form className="itinerary-form" onSubmit={handleSubmit}>
      <div className="form-group">
        <label htmlFor="title">Title *</label>
        <input
          type="text"
          id="title"
          name="title"
          value={formData.title}
          onChange={handleChange}
          required
          placeholder="e.g., Summer Trip to Europe"
        />
      </div>

      <div className="form-group">
        <label htmlFor="destination">Destination *</label>
        <input
          type="text"
          id="destination"
          name="destination"
          value={formData.destination}
          onChange={handleChange}
          required
          placeholder="e.g., Paris, France"
        />
      </div>

      <div className="form-row">
        <div className="form-group">
          <label htmlFor="startDate">Start Date *</label>
          <input
            type="date"
            id="startDate"
            name="startDate"
            value={formData.startDate}
            onChange={handleChange}
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="endDate">End Date *</label>
          <input
            type="date"
            id="endDate"
            name="endDate"
            value={formData.endDate}
            onChange={handleChange}
            required
          />
        </div>
      </div>

      <div className="form-group">
        <label htmlFor="description">Description</label>
        <textarea
          id="description"
          name="description"
          value={formData.description}
          onChange={handleChange}
          rows={4}
          placeholder="Describe your itinerary..."
        />
      </div>

      <div className="form-row">
        <div className="form-group">
          <label htmlFor="status">Status</label>
          <select
            id="status"
            name="status"
            value={formData.status}
            onChange={handleChange}
          >
            <option value="draft">Draft</option>
            <option value="confirmed">Confirmed</option>
            <option value="completed">Completed</option>
            <option value="cancelled">Cancelled</option>
          </select>
        </div>

        <div className="form-group">
          <label htmlFor="currency">Currency</label>
          <select
            id="currency"
            name="currency"
            value={formData.currency}
            onChange={handleChange}
          >
            <option value="USD">USD</option>
            <option value="EUR">EUR</option>
            <option value="GBP">GBP</option>
            <option value="JPY">JPY</option>
            <option value="CAD">CAD</option>
            <option value="AUD">AUD</option>
          </select>
        </div>

        <div className="form-group">
          <label htmlFor="budget">Budget</label>
          <input
            type="number"
            id="budget"
            name="budget"
            value={formData.budget || ''}
            onChange={handleChange}
            min="0"
            step="0.01"
            placeholder="0.00"
          />
        </div>
      </div>

      <div className="form-actions">
        <button type="submit" className="btn btn-primary" disabled={loading}>
          {loading ? 'Saving...' : initialData ? 'Update Itinerary' : 'Create Itinerary'}
        </button>
        {onCancel && (
          <button type="button" className="btn btn-secondary" onClick={onCancel}>
            Cancel
          </button>
        )}
      </div>
    </form>
  );
};

export default ItineraryForm;

// frontend-vue/src/components/ItineraryForm.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import type { Itinerary, ItineraryFormData } from '@/types'

interface Props {
  initialData?: Partial<Itinerary>
  isLoading?: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  submit: [data: ItineraryFormData]
  cancel: []
}>()

const formData = ref<ItineraryFormData>({
  title: props.initialData?.title || '',
  destination: props.initialData?.destination || '',
  startDate: props.initialData?.startDate || '',
  endDate: props.initialData?.endDate || '',
  description: props.initialData?.description || ''
})

const errors = ref<Record<string, string>>({})

const validateForm = (): boolean => {
  errors.value = {}

  if (!formData.value.title.trim()) {
    errors.value.title = 'Title is required'
  }

  if (!formData.value.destination.trim()) {
    errors.value.destination = 'Destination is required'
  }

  if (!formData.value.startDate) {
    errors.value.startDate = 'Start date is required'
  }

  if (!formData.value.endDate) {
    errors.value.endDate = 'End date is required'
  }

  if (formData.value.startDate && formData.value.endDate) {
    if (new Date(formData.value.endDate) < new Date(formData.value.startDate)) {
      errors.value.endDate = 'End date must be after start date'
    }
  }

  return Object.keys(errors.value).length === 0
}

const handleSubmit = () => {
  if (validateForm()) {
    emit('submit', formData.value)
  }
}

const handleCancel = () => {
  emit('cancel')
}

const isFormValid = computed(() => {
  return formData.value.title.trim() && 
         formData.value.destination.trim() && 
         formData.value.startDate && 
         formData.value.endDate
})
</script>

<template>
  <form @submit.prevent="handleSubmit" class="itinerary-form">
    <div class="form-group">
      <label for="title" class="form-label">Trip Title *</label>
      <input
        id="title"
        v-model="formData.title"
        type="text"
        class="form-input"
        :class="{ 'error': errors.title }"
        placeholder="e.g., Summer Vacation in Europe"
        maxlength="255"
      />
      <div v-if="errors.title" class="form-error">{{ errors.title }}</div>
    </div>

    <div class="form-group">
      <label for="destination" class="form-label">Destination *</label>
      <input
        id="destination"
        v-model="formData.destination"
        type="text"
        class="form-input"
        :class="{ 'error': errors.destination }"
        placeholder="e.g., Paris, France"
        maxlength="255"
      />
      <div v-if="errors.destination" class="form-error">{{ errors.destination }}</div>
    </div>

    <div class="form-row">
      <div class="form-group">
        <label for="startDate" class="form-label">Start Date *</label>
        <input
          id="startDate"
          v-model="formData.startDate"
          type="date"
          class="form-input"
          :class="{ 'error': errors.startDate }"
        />
        <div v-if="errors.startDate" class="form-error">{{ errors.startDate }}</div>
      </div>

      <div class="form-group">
        <label for="endDate" class="form-label">End Date *</label>
        <input
          id="endDate"
          v-model="formData.endDate"
          type="date"
          class="form-input"
          :class="{ 'error': errors.endDate }"
        />
        <div v-if="errors.endDate" class="form-error">{{ errors.endDate }}</div>
      </div>
    </div>

    <div class="form-group">
      <label for="description" class="form-label">Description (Optional)</label>
      <textarea
        id="description"
        v-model="formData.description"
        class="form-textarea"
        placeholder="Add any additional details about your trip..."
        rows="4"
      ></textarea>
      <div class="form-hint">Provide a brief overview of your trip</div>
    </div>

    <div class="form-actions">
      <button
        type="button"
        @click="handleCancel"
        class="btn btn-secondary"
        :disabled="isLoading"
      >
        Cancel
      </button>
      <button
        type="submit"
        class="btn btn-primary"
        :disabled="!isFormValid || isLoading"
      >
        {{ isLoading ? 'Saving...' : (initialData ? 'Update Itinerary' : 'Create Itinerary') }}
      </button>
    </div>
  </form>
</template>

<style scoped>
.itinerary-form {
  background: white;
  padding: 2rem;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.form-row {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
}

.form-input.error,
.form-textarea.error {
  border-color: #dc3545;
}

.form-actions {
  display: flex;
  gap: 1rem;
  justify-content: flex-end;
  margin-top: 2rem;
  padding-top: 1.5rem;
  border-top: 1px solid #eee;
}

@media (max-width: 768px) {
  .form-row {
    grid-template-columns: 1fr;
  }

  .form-actions {
    flex-direction: column-reverse;
  }

  .form-actions .btn {
    width: 100%;
  }
}
</style>
